chat_config:
  model: gpt-3.5-turbo-1106
  temperature: 0

context_agent_config:
  model: gpt-4-1106-preview
  temperature: 0

writing_agent_config:
  model: gpt-4-1106-preview
  temperature: 0

search_agent_config:
  model: gpt-4-1106-preview
  temperature: 0

codebase_config:
  include_file_patterns:
  - '*.py'
  - '*.java'
  - '*.js'
  - '*.ts'
  - '*.cs'
  - '*.rs'
  - '*.rb'
  - '*.c'
  - '*.go'
  - '*.php'
  exclude_patterns:
  - .*
  - __*
